name: Sync with Upstream

on:
  schedule:
    # 每 5 小时运行一次
    - cron: '5 */5 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 配置 Git 用户信息
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "smgw352@gmail.com"

      # 添加上游仓库为 remote
      - name: Add upstream repository
        run: git remote add upstream https://github.com/qist/tvbox.git

      # 获取目标仓库的默认分支名称
      - name: Get default branch of upstream
        run: |
          DEFAULT_BRANCH=$(git remote show upstream | grep "HEAD branch" | awk '{print $NF}')
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV

      # 获取目标仓库的最新更新
      - name: Fetch upstream
        run: git fetch upstream

      # 合并最新代码到当前分支
      - name: Merge upstream changes
        run: git merge upstream/${{ env.DEFAULT_BRANCH }} --allow-unrelated-histories -m "Merge upstream changes"

      # 推送合并后的代码到 Fork
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin master
